//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public cart()
        {
            this.cart_items = new HashSet<cart_items>();
            this.customers = new HashSet<customer>();
        }
    
        public int id { get; set; }
    
        public virtual ICollection<cart_items> cart_items { get; set; }
        public virtual ICollection<customer> customers { get; set; }
    }
}
