//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.ratings = new HashSet<rating>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int phone { get; set; }
        public string address { get; set; }
        public Nullable<int> cart_id { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual ICollection<rating> ratings { get; set; }
    }
}
