//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.ratings = new HashSet<rating>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public int price { get; set; }
        public byte[] img { get; set; }
        public string category { get; set; }
        public Nullable<int> seller_id { get; set; }
        public int quantity { get; set; }
        public Nullable<double> product_rate { get; set; }
    
        public virtual seller seller { get; set; }
        public virtual ICollection<rating> ratings { get; set; }
    }
}
