//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Market
{
    using System;
    using System.Collections.Generic;
    
    public partial class seller
    {
        public seller()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int phone { get; set; }
        public Nullable<int> balance { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
